# Build settings

markdown: kramdown
permalink: none
plugins: [jekyll-sitemap, jekyll-seo-tag]

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Site settings:
#   title is used for the logo
#   title, description, and author are all used to populate <meta> tags for SEO

title:        "Portfolio"
description:  "Powered by Jekyll and GitHub Pages"
author:       "Rachel Bannerman"
