# Build settings

markdown: kramdown
permalink: none
plugins: [jekyll-sitemap, jekyll-seo-tag]
include: ['_pages']

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Project categories

collections_dir: categories
collections:
  design:
    name: 'Design/Technical'
    weight: 0
    output: true
  performance:
    name: "Performance"
    weight: 1
    output: true
  interdisciplinary:
    name: "Interdisciplinary"
    weight: 2
    output: true
  written:
    name: "Written Work"
    weight: 3
    output: true

# Site settings:
#   title is used for the logo
#   title, description, and author are all used to populate <meta> tags for SEO

title:        "Portfolio"
description:  "Powered by Jekyll and GitHub Pages"
author:       "Rachel Bannerman"
